from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pandas as pd


def _latest_extract() -> Path | None:
    # This finds the newest extract file without hardcoding the date range.
    extracts = sorted(Path("data/extracts").glob("events_daily_*.csv"))
    return extracts[-1] if extracts else None


def main() -> None:
    # This writes a single “latest.md” so the repo doesn’t fill up with daily logs.
    out_dir = Path("reports/runlogs")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "latest.md"

    extract_path = _latest_extract()

    lines: list[str] = []
    lines.append("# Run Log (latest)")
    lines.append("")
    lines.append(f"- run_timestamp: {datetime.now().isoformat(timespec='seconds')}")
    lines.append("")

    if extract_path is None:
        lines.append("## Extract")
        lines.append("- status: no extract file found in `data/extracts/`")
    else:
        df = pd.read_csv(extract_path, low_memory=False)
        lines.append("## Extract")
        lines.append(f"- file: `{extract_path.as_posix()}`")
        lines.append(f"- rows: {len(df):,}")
        if "SQLDATE" in df.columns:
            lines.append(f"- min(SQLDATE): {df['SQLDATE'].min()}")
            lines.append(f"- max(SQLDATE): {df['SQLDATE'].max()}")

    lines.append("")
    lines.append("## Notes")
    lines.append("- This log is generated by `python src/write_run_log.py` (or `make runlog`).")
    lines.append("- BigQuery validation checks live in `docs/OPERATIONS.md`.")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote: {out_path.as_posix()}")


if __name__ == "__main__":
    main()
